apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: dev
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: {{.Values.image.repository }}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy }}
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.env.SPRING_PROFILES_ACTIVE }}
          # Ajout de health checks
          readinessProbe:
            httpGet:
              path: {{.Values.readinessProbe.path }}
              port: {{.Values.readinessProbe.port }}
            initialDelaySeconds: {{.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.path }}
              port: {{.Values.livenessProbe.port }}
            initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.livenessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: {{.Values.service.type}}
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      nodePort: {{.Values.service.nodePort}}


