apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: 10.0.0.119:5000/ahmed_personnel/bookmarkr:main-20250911-1457
          imagePullPolicy: Always
          ports:
            - containerPort: 8091

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          # Ajout de health checks
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30081
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-search
  namespace: dev   # 👈 ton namespace app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-search
  namespace: dev   # 👈 ton namespace app
subsets:
  - addresses:
      - ip: 10.0.0.119
    ports:
      - port: 3306
